services:
  website:
    image: ghcr.io/ipnet-mesh/website:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    volumes:
      - ./assets/data:/app/assets/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/', timeout=3)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
