services:
  website:
    build: .
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    volumes:
      - ./assets/data:/app/assets/data:ro
      - ./templates:/app/templates:ro
      - ./assets/js:/app/assets/js:ro
